extends Node2D
## Fog overlay only.
## Draws fog based on the rooms generated by main.gd and the FogOfWar autoload.
## This script does NOT generate the map or touch gameplay systems.

const UNEXPLORED_COLOR := Color(0.0, 0.0, 0.0, 0.90)
const EXPLORED_COLOR := Color(0.0, 0.0, 0.0, 0.55)
const BORDER_COLOR := Color(0.0, 0.0, 0.0, 0.18)

func _ready() -> void:
	z_index = 100
	set_process(false)
	queue_redraw()


func _notification(what: int) -> void:
	if what == NOTIFICATION_VISIBILITY_CHANGED:
		queue_redraw()


func _draw() -> void:
	var main := get_parent()
	if main == null:
		return

	# Dev/tutorial/sandbox mode can disable fog entirely.
	if bool(main.get("_dev_fog_off")):
		return

	var rooms: Array = main.get("rooms")
	if rooms == null or rooms.is_empty():
		return

	for room in rooms:
		if room == null or not is_instance_valid(room):
			continue
		if not room.has_method("get_rect"):
			continue

		var rect: Rect2 = room.get_rect()
		var rid: int = int(room.get("room_id"))

		var draw_color := UNEXPLORED_COLOR
		if FogOfWar.is_active(rid):
			continue
		elif FogOfWar.is_explored(rid):
			draw_color = EXPLORED_COLOR

		draw_rect(rect, draw_color, true)
		draw_rect(rect, BORDER_COLOR, false, 2.0)
